nav:
  - Getting Started:
      - Introduction: index.md
      - Setup: setup.md
      - Deployment:
        - Configuration: Configuration.md
        - Deploy with Docker: Deployment.md
        - User system: Users.md
  - User guide:
      - Introduction: user-guide/index.md
  - Backend development:
      - Introduction: dev-backend/index.md
      - API specification: dev-backend/api.md
      - Development environment: dev-backend/Development-instructions.md
      - Testing locally: Testing.md
  - Frontend development:
      - Introduction: dev-frontend/index.md
site_name: Gramps Web
site_url: https://gramps-project.github.io/web
edit_uri: https://github.com/gramps-project/web/blob/main/docs/
theme:
  name: "material"
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.expand
  palette:
    scheme: default
    primary: brown
    accent: blue
  logo: logo.svg
  favicon: favicon.ico
plugins:
  - search
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
